apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: "nifi"
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - name: nifi
        image: apache/nifi:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /opt/nifi/nifi-current
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nifi-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  labels:
    app: nifi
spec:
  type: LoadBalancer  # Can use NodePort if needed
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nifi
